### ISSUE TITLE
Datapack failed to load

### ISSUE THREAD

**Issue by frank89722** [Trinsdar/GT-4-Renewed#29]
With only these three mods installed:
gt4r-0.0.2
antimatter-1.16.5-0.0.4
tesseract-1.16.5-0.0.4

Forge 36.1.4

[latest.log](https://github.com/Trinsdar/GT-4-Reimagined/files/6981393/latest.log)

**Comment by Trinsdar** [comment]
Oh woops, looks like i need to go delete the generated tag jsons

**Comment by Trinsdar** [comment]
was fixed in a hotfix, closing
