### ISSUE TITLE
Player attribute injection mixin prevents other mods from adding their attributes

### ISSUE THREAD

**Issue by Hubry** [Trinsdar/GT-4-Renewed#31]
Originally reported at https://github.com/VazkiiMods/Botania/issues/3814

`setReturnValue` makes the method return, which makes our pixie summon chance attribute not get added. In our case this causes crashes every time a player takes damage.

https://github.com/Trinsdar/GT-4-Reimagined/blob/c89641b99f4c5a32b104e4b27e2114f762075869/src/main/java/trinsdar/gt4r/mixin/PlayerEntityMixin.java#L39-L42

**Comment by Trinsdar** [comment]
ah ok thanks for the info, should be fixed now
